//! Console commands registered by psycho-nvse.

use libnvse::nvse_command;
use libnvse::plugin::PluginContext;

use crate::mods::heap_replacer::gheap::engine::cell_unload;
use crate::mods::heap_replacer::mem_stats;
use crate::mods::heap_replacer::gheap::{allocator, slab};

// ---------------------------------------------------------------------------
// Command handlers (generated by nvse_command! macro)
// ---------------------------------------------------------------------------

nvse_command!(PsychoMem, cmd, {
    let report = mem_stats::MemStats::detailed_report();
    for line in report.lines() {
        cmd.print(line);
    }
    true
});

nvse_command!(PsychoMemMB, cmd, {
    let info = libmimalloc::process_info::MiMallocProcessInfo::get();
    let mb = (info.get_current_commit() / 1024 / 1024) as f64;
    cmd.print(&format!("{:.0} MB", mb));
    cmd.set_result(mb);
    true
});

nvse_command!(PsychoMemBytes, cmd, {
    let info = libmimalloc::process_info::MiMallocProcessInfo::get();
    let bytes = info.get_current_commit() as f64;
    cmd.print(&format!("{} bytes", bytes as u64));
    cmd.set_result(bytes);
    true
});

nvse_command!(PsychoSBM, cmd, {
    let stats = mem_stats::global();
    let sbm2_mb = stats.sbm2_allocated() as f64 / 1024.0 / 1024.0;
    cmd.print(&format!("SBM2 allocated: {:.1} MB", sbm2_mb));

    let pressure_cycles = stats.pressure_cycles();
    if pressure_cycles > 0 {
        cmd.print(&format!(
            "Pressure: {} cycles, {} cells freed (pressure)",
            pressure_cycles, stats.pressure_cells_unloaded()
        ));
    } else {
        cmd.print("Pressure: no events");
    }

    let unload_cycles = cell_unload::total_cycles();
    if unload_cycles > 0 {
        cmd.print(&format!(
            "Cell unload: {} cells in {} cycles, freed {}MB",
            cell_unload::total_cells_unloaded(),
            unload_cycles,
            cell_unload::total_bytes_freed() / 1024 / 1024,
        ));
    }

    cmd.set_result(sbm2_mb);
    true
});

nvse_command!(PsychoMemHud, _cmd, {
    let summary = mem_stats::MemStats::hud_summary();
    let _ = libnvse::api::hud::hud_message(&summary);
    true
});

nvse_command!(PsychoQuarantine, cmd, {
    let bytes = slab::committed_bytes();
    let mb = bytes as f64 / 1024.0 / 1024.0;

    cmd.print("=== Quarantine Status ===");
    cmd.print(&format!("Quarantine buffer:   {:.1} MB", mb));
    cmd.print(&format!("Is main thread:      {}", allocator::is_main_thread()));
    true
});

nvse_command!(PsychoCellUnload, cmd, {
    let info = libmimalloc::process_info::MiMallocProcessInfo::get();
    let commit_mb = info.get_current_commit() / 1024 / 1024;
    let quarantine_mb = slab::committed_bytes() / 1024 / 1024;

    cmd.print("=== Cell Unload ===");
    cmd.print(&format!("Current: commit={}MB, quarantine={}MB", commit_mb, quarantine_mb));
    cmd.print(&format!(
        "Lifetime: {} cells unloaded in {} cycles, freed {}MB total",
        cell_unload::total_cells_unloaded(),
        cell_unload::total_cycles(),
        cell_unload::total_bytes_freed() / 1024 / 1024,
    ));
    cmd.print("Requesting 20 cells at next AI_JOIN...");

    cell_unload::request_deferred(20);
    true
});

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

pub fn register(ctx: &mut PluginContext) {
    let cmds: &[(&str, &str, &str, libnvse::Cmd_Execute)] = &[
        ("PsychoMem",      "pmem",   "Detailed memory report",         PSYCHOMEM_EXECUTE),
        ("PsychoMemMB",    "pmemmb", "Get committed memory in MB",     PSYCHOMEMMB_EXECUTE),
        ("PsychoMemBytes", "pmemb",  "Get committed memory in bytes",  PSYCHOMEMBYTES_EXECUTE),
        ("PsychoSBM",      "psbm",   "SBM2 scrap heap stats",         PSYCHOSBM_EXECUTE),
        ("PsychoMemHud",   "pmemh",  "Show memory HUD notification",  PSYCHOMEMHUD_EXECUTE),
        ("PsychoQuarantine", "pquar", "Show quarantine status",       PSYCHOQUARANTINE_EXECUTE),
        ("PsychoCellUnload", "pcell", "Force cell unload + memory reclaim", PSYCHOCELLUNLOAD_EXECUTE),
    ];

    for (name, short, help, execute) in cmds {
        match ctx.register_command(name, short, help, false, &[], *execute) {
            Ok(_) => log::info!("[OK] Command: {}", name),
            Err(e) => log::error!("[FAIL] Command {}: {}", name, e),
        }
    }
}
