//! Console commands registered by psycho-nvse.

use libnvse::nvse_command;
use libnvse::plugin::PluginContext;

use crate::mods::heap_replacer::gheap::engine::cell_unload;
use crate::mods::heap_replacer::gheap::{allocator, block, pool, va_alloc};
use crate::mods::heap_replacer::{HeapReplacerMode, current_mode, mem_stats, scrap_heap};

// ---------------------------------------------------------------------------
// Command handlers (generated by nvse_command! macro)
// ---------------------------------------------------------------------------

nvse_command!(PsychoMem, cmd, {
    let report = mem_stats::MemStats::detailed_report();
    for line in report.lines() {
        cmd.print(line);
    }
    true
});

nvse_command!(PsychoMemMB, cmd, {
    let bytes = mem_stats::current_allocator_bytes();
    let mb = bytes as f64 / 1024.0 / 1024.0;
    cmd.print(&format!(
        "{}: {:.1} MB",
        mem_stats::current_allocator_name(),
        mb,
    ));
    cmd.set_result(mb);
    true
});

nvse_command!(PsychoMemBytes, cmd, {
    let bytes = mem_stats::current_allocator_bytes();
    cmd.print(&format!(
        "{}: {} bytes",
        mem_stats::current_allocator_name(),
        bytes,
    ));
    let bytes = bytes as f64;
    cmd.set_result(bytes);
    true
});

nvse_command!(PsychoScrapHeap, cmd, {
    let stats = mem_stats::global();
    let scrap = scrap_heap::snapshot();
    let scrap_heap_mb = scrap.live_bytes as f64 / 1024.0 / 1024.0;
    cmd.print("=== scrap_heap ===");
    cmd.print(&format!("Live capacity: {:.1} MB", scrap_heap_mb));
    cmd.print(&format!(
        "Identities: {} total, {} active",
        scrap.identities, scrap.active_identities,
    ));
    cmd.print(&format!(
        "Regions: {} | live allocations: {}",
        scrap.regions, scrap.live_allocs,
    ));

    let pressure_cycles = stats.pressure_cycles();
    if pressure_cycles > 0 {
        cmd.print(&format!(
            "Pressure: {} cycles, {} cells freed (pressure)",
            pressure_cycles,
            stats.pressure_cells_unloaded()
        ));
    } else {
        cmd.print("Pressure: no events");
    }

    let unload_cycles = cell_unload::total_cycles();
    if unload_cycles > 0 {
        cmd.print(&format!(
            "Cell unload: {} cells in {} cycles, freed {}MB",
            cell_unload::total_cells_unloaded(),
            unload_cycles,
            cell_unload::total_bytes_freed() / 1024 / 1024,
        ));
    }

    cmd.set_result(scrap_heap_mb);
    true
});

nvse_command!(PsychoMemHud, _cmd, {
    let summary = mem_stats::MemStats::hud_summary();
    let _ = libnvse::api::hud::hud_message(&summary);
    true
});

nvse_command!(PsychoQuarantine, cmd, {
    if current_mode() != Some(HeapReplacerMode::Full) {
        cmd.print("gheap is disabled; light_mode uses scrap_heap only");
        return true;
    }

    let pool_mb = pool::committed_bytes() as f64 / 1024.0 / 1024.0;
    let block_mb = block::committed_bytes() as f64 / 1024.0 / 1024.0;
    let va_mb = va_alloc::live_bytes() as f64 / 1024.0 / 1024.0;

    cmd.print("=== gheap Status ===");
    cmd.print(&format!("Pool committed:      {:.1} MB", pool_mb));
    cmd.print(&format!(
        "Pool reserved:       {} MB",
        pool::reserved_bytes() / 1024 / 1024
    ));
    cmd.print(&format!("Pool live cells:     {}", pool::live_cells()));
    cmd.print(&format!(
        "Pool deferred free:  {}",
        pool::deferred_free_cells()
    ));
    cmd.print(&format!(
        "Block committed:     {:.1} MB ({} blocks)",
        block_mb,
        block::block_count()
    ));
    cmd.print(&format!(
        "Direct VA:           {:.1} MB ({} blocks, {} fails)",
        va_mb,
        va_alloc::live_count(),
        va_alloc::fail_count(),
    ));
    cmd.print(&format!(
        "Is main thread:      {}",
        allocator::is_main_thread()
    ));
    true
});

nvse_command!(PsychoCellUnload, cmd, {
    if current_mode() != Some(HeapReplacerMode::Full) {
        cmd.print("Cell unload reclaim is gheap-only; light_mode uses scrap_heap only");
        return true;
    }

    let owned_mb = mem_stats::current_allocator_bytes() / 1024 / 1024;
    let pool_mb = pool::committed_bytes() / 1024 / 1024;

    cmd.print("=== Cell Unload ===");
    cmd.print(&format!(
        "Current: gheap={}MB, pool={}MB",
        owned_mb, pool_mb
    ));
    cmd.print(&format!(
        "Lifetime: {} cells unloaded in {} cycles, freed {}MB total",
        cell_unload::total_cells_unloaded(),
        cell_unload::total_cycles(),
        cell_unload::total_bytes_freed() / 1024 / 1024,
    ));
    cmd.print("Requesting 20 cells at next AI_JOIN...");

    cell_unload::request_deferred(20);
    true
});

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

pub fn register(ctx: &mut PluginContext) {
    let cmds: &[(&str, &str, &str, libnvse::Cmd_Execute)] = &[
        (
            "PsychoMem",
            "pmem",
            "Detailed memory report",
            PSYCHOMEM_EXECUTE,
        ),
        (
            "PsychoMemMB",
            "pmemmb",
            "Get committed memory in MB",
            PSYCHOMEMMB_EXECUTE,
        ),
        (
            "PsychoMemBytes",
            "pmemb",
            "Get committed memory in bytes",
            PSYCHOMEMBYTES_EXECUTE,
        ),
        (
            "PsychoScrapHeap",
            "pscrap",
            "scrap_heap stats",
            PSYCHOSCRAPHEAP_EXECUTE,
        ),
        (
            "PsychoMemHud",
            "pmemh",
            "Show memory HUD notification",
            PSYCHOMEMHUD_EXECUTE,
        ),
        (
            "PsychoQuarantine",
            "pquar",
            "Show quarantine status",
            PSYCHOQUARANTINE_EXECUTE,
        ),
        (
            "PsychoCellUnload",
            "pcell",
            "Force cell unload + memory reclaim",
            PSYCHOCELLUNLOAD_EXECUTE,
        ),
    ];

    for (name, short, help, execute) in cmds {
        match ctx.register_command(name, short, help, false, &[], *execute) {
            Ok(_) => log::info!("[OK] Command: {}", name),
            Err(e) => log::error!("[FAIL] Command {}: {}", name, e),
        }
    }
}
