//! Console commands registered by psycho-nvse.

use libnvse::nvse_command;
use libnvse::plugin::PluginContext;

use crate::mods::memory::mem_stats;
use crate::mods::memory::game_heap::delayed_free;

// ---------------------------------------------------------------------------
// Command handlers (generated by nvse_command! macro)
// ---------------------------------------------------------------------------

nvse_command!(PsychoMem, cmd, {
    let report = mem_stats::MemStats::detailed_report();
    for line in report.lines() {
        cmd.print(line);
    }
    true
});

nvse_command!(PsychoMemMB, cmd, {
    let info = libmimalloc::process_info::MiMallocProcessInfo::get();
    let mb = (info.get_current_commit() / 1024 / 1024) as f64;
    cmd.print(&format!("{:.0} MB", mb));
    cmd.set_result(mb);
    true
});

nvse_command!(PsychoMemBytes, cmd, {
    let info = libmimalloc::process_info::MiMallocProcessInfo::get();
    let bytes = info.get_current_commit() as f64;
    cmd.print(&format!("{} bytes", bytes as u64));
    cmd.set_result(bytes);
    true
});

nvse_command!(PsychoSBM, cmd, {
    let stats = mem_stats::global();
    let sbm2_mb = stats.sbm2_allocated() as f64 / 1024.0 / 1024.0;
    cmd.print(&format!("SBM2 allocated: {:.1} MB", sbm2_mb));

    let cycles = stats.pressure_cycles();
    if cycles > 0 {
        cmd.print(&format!(
            "Pressure: {} cycles, {} cells freed",
            cycles, stats.pressure_cells_unloaded()
        ));
    } else {
        cmd.print("Pressure: no events");
    }
    cmd.set_result(sbm2_mb);
    true
});

nvse_command!(PsychoMemHud, _cmd, {
    let summary = mem_stats::MemStats::hud_summary();
    let _ = libnvse::api::hud::hud_message(&summary);
    true
});

nvse_command!(PsychoQuarantine, cmd, {
    let bytes = delayed_free::get_quarantine_usage();
    let mb = bytes as f64 / 1024.0 / 1024.0;

    cmd.print(&format!("=== Quarantine Status ==="));
    cmd.print(&format!("Quarantine buffer:   {:.1} MB", mb));
    cmd.print(&format!("Is main thread:      {}", delayed_free::is_main_thread()));
    true
});

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

pub fn register(ctx: &mut PluginContext) {
    let cmds: &[(&str, &str, &str, libnvse::Cmd_Execute)] = &[
        ("PsychoMem",      "pmem",   "Detailed memory report",         PSYCHOMEM_EXECUTE),
        ("PsychoMemMB",    "pmemmb", "Get committed memory in MB",     PSYCHOMEMMB_EXECUTE),
        ("PsychoMemBytes", "pmemb",  "Get committed memory in bytes",  PSYCHOMEMBYTES_EXECUTE),
        ("PsychoSBM",      "psbm",   "SBM2 scrap heap stats",         PSYCHOSBM_EXECUTE),
        ("PsychoMemHud",   "pmemh",  "Show memory HUD notification",  PSYCHOMEMHUD_EXECUTE),
        ("PsychoQuarantine", "pquar", "Show quarantine status",       PSYCHOQUARANTINE_EXECUTE),
    ];

    for (name, short, help, execute) in cmds {
        match ctx.register_command(name, short, help, false, &[], *execute) {
            Ok(_) => log::info!("[OK] Command: {}", name),
            Err(e) => log::error!("[FAIL] Command {}: {}", name, e),
        }
    }
}
