//! Behavior-neutral trajectory math for Ballistics shadow comparison.
//!
//! This module never reads or writes engine memory. It advances Atom-owned
//! state analytically under constant acceleration and exposes a bounded chord
//! view for later collision comparison. Runtime admission remains separate:
//! callers must supply only capability-proven native speed and acceleration.

use thiserror::Error;

/// Hard upper bound for collision chords generated by one shadow update.
pub const MAX_CHORD_SEGMENTS: u8 = 8;

/// Failure to initialize or advance a shadow trajectory safely.
#[derive(Clone, Copy, Debug, Error, PartialEq)]
pub enum ShadowFlightError {
    /// Position, direction, velocity, or acceleration was not finite.
    #[error("shadow trajectory contains a non-finite vector")]
    NonFiniteVector,
    /// Direction had no usable magnitude.
    #[error("shadow trajectory direction is zero")]
    ZeroDirection,
    /// Effective native speed was non-finite or non-positive.
    #[error("shadow trajectory speed must be finite and positive")]
    InvalidSpeed,
    /// Frame time was non-finite or non-positive.
    #[error("shadow trajectory delta must be finite and positive")]
    InvalidDelta,
    /// Chord error tolerance was non-finite or non-positive.
    #[error("shadow trajectory chord tolerance must be finite and positive")]
    InvalidChordTolerance,
    /// Analytic integration overflowed finite `f32` state.
    #[error("shadow trajectory integration overflowed")]
    IntegrationOverflow,
}

/// Atom-owned position and velocity used only for native-flight comparison.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ShadowFlight {
    position: [f32; 3],
    velocity: [f32; 3],
}

impl ShadowFlight {
    /// Initialize a trajectory from a position, direction, and effective speed.
    ///
    /// Direction is normalized so content-provided vector magnitude cannot
    /// silently scale the native effective speed.
    pub fn new(
        position: [f32; 3],
        direction: [f32; 3],
        effective_speed: f32,
    ) -> Result<Self, ShadowFlightError> {
        if !finite_vector(position) || !finite_vector(direction) {
            return Err(ShadowFlightError::NonFiniteVector);
        }
        if !effective_speed.is_finite() || effective_speed <= 0.0 {
            return Err(ShadowFlightError::InvalidSpeed);
        }
        let magnitude_squared = dot(direction, direction);
        if !magnitude_squared.is_finite() || magnitude_squared <= f32::EPSILON {
            return Err(ShadowFlightError::ZeroDirection);
        }
        let scale = effective_speed / magnitude_squared.sqrt();
        let velocity = multiply(direction, scale);
        if !finite_vector(velocity) {
            return Err(ShadowFlightError::IntegrationOverflow);
        }
        Ok(Self { position, velocity })
    }

    /// Return the current shadow position.
    pub const fn position(self) -> [f32; 3] {
        self.position
    }

    /// Return the current shadow velocity.
    pub const fn velocity(self) -> [f32; 3] {
        self.velocity
    }

    /// Advance with analytic constant-acceleration integration.
    ///
    /// The returned step divides its parabola into at most eight chords. If
    /// the requested tolerance needs more, `chord_limit_reached` is true and
    /// the caller must retain native behavior rather than starting an
    /// unbounded catch-up loop. An error leaves this state unchanged.
    pub fn advance(
        &mut self,
        acceleration: [f32; 3],
        delta_seconds: f32,
        max_chord_error: f32,
    ) -> Result<ShadowStep, ShadowFlightError> {
        if !finite_vector(acceleration) {
            return Err(ShadowFlightError::NonFiniteVector);
        }
        if !delta_seconds.is_finite() || delta_seconds <= 0.0 {
            return Err(ShadowFlightError::InvalidDelta);
        }
        if !max_chord_error.is_finite() || max_chord_error <= 0.0 {
            return Err(ShadowFlightError::InvalidChordTolerance);
        }

        let delta_squared = delta_seconds * delta_seconds;
        let end_position = add(
            add(self.position, multiply(self.velocity, delta_seconds)),
            multiply(acceleration, 0.5 * delta_squared),
        );
        let end_velocity = add(self.velocity, multiply(acceleration, delta_seconds));
        if !finite_vector(end_position) || !finite_vector(end_velocity) {
            return Err(ShadowFlightError::IntegrationOverflow);
        }

        // A constant-acceleration parabola deviates furthest from its chord at
        // the midpoint by |a|*dt^2/8. Splitting into n equal chords reduces
        // that bound by n^2, so ceil(sqrt(error/tolerance)) is sufficient.
        let acceleration_magnitude = dot(acceleration, acceleration).sqrt();
        let maximum_deviation = acceleration_magnitude * delta_squared * 0.125;
        if !maximum_deviation.is_finite() {
            return Err(ShadowFlightError::IntegrationOverflow);
        }
        let required = (maximum_deviation / max_chord_error).sqrt().ceil().max(1.0);
        let chord_limit_reached = required > f32::from(MAX_CHORD_SEGMENTS);
        let chord_segments = required.min(f32::from(MAX_CHORD_SEGMENTS)) as u8;

        let step = ShadowStep {
            start_position: self.position,
            start_velocity: self.velocity,
            acceleration,
            delta_seconds,
            end_position,
            end_velocity,
            chord_segments,
            chord_limit_reached,
        };
        self.position = end_position;
        self.velocity = end_velocity;
        Ok(step)
    }
}

/// One analytic shadow-flight update with bounded chord subdivision.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ShadowStep {
    start_position: [f32; 3],
    start_velocity: [f32; 3],
    acceleration: [f32; 3],
    delta_seconds: f32,
    end_position: [f32; 3],
    end_velocity: [f32; 3],
    chord_segments: u8,
    chord_limit_reached: bool,
}

impl ShadowStep {
    /// Return the analytic end position.
    pub const fn end_position(self) -> [f32; 3] {
        self.end_position
    }

    /// Return the analytic end velocity.
    pub const fn end_velocity(self) -> [f32; 3] {
        self.end_velocity
    }

    /// Return the number of bounded chords in this update.
    pub const fn chord_segments(self) -> u8 {
        self.chord_segments
    }

    /// Return whether the requested error bound needed more than eight chords.
    pub const fn chord_limit_reached(self) -> bool {
        self.chord_limit_reached
    }

    /// Return one chord by zero-based index.
    ///
    /// No collection is allocated; callers can iterate `0..chord_segments()`
    /// and consume one pair of endpoints at a time.
    pub fn chord(self, index: u8) -> Option<([f32; 3], [f32; 3])> {
        if index >= self.chord_segments {
            return None;
        }
        let count = f32::from(self.chord_segments);
        let start_time = self.delta_seconds * (f32::from(index) / count);
        let end_time = self.delta_seconds * (f32::from(index + 1) / count);
        Some((self.position_at(start_time), self.position_at(end_time)))
    }

    fn position_at(self, time: f32) -> [f32; 3] {
        add(
            add(self.start_position, multiply(self.start_velocity, time)),
            multiply(self.acceleration, 0.5 * time * time),
        )
    }
}

fn finite_vector(value: [f32; 3]) -> bool {
    value.into_iter().all(f32::is_finite)
}

fn dot(left: [f32; 3], right: [f32; 3]) -> f32 {
    left.into_iter().zip(right).map(|(a, b)| a * b).sum()
}

fn add(left: [f32; 3], right: [f32; 3]) -> [f32; 3] {
    [left[0] + right[0], left[1] + right[1], left[2] + right[2]]
}

fn multiply(value: [f32; 3], scale: f32) -> [f32; 3] {
    [value[0] * scale, value[1] * scale, value[2] * scale]
}
