[package]
name = "atom"
version = "0.1.0"
edition = "2024"

[lib]
name = "atom"
crate-type = ["cdylib", "rlib"]

[dependencies]
libnvse = { path = "../libnvse" }
libpsycho = { path = "../libpsycho" }
log = { workspace = true }
serde = { workspace = true }
serini = "0.3.0"
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
